name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      if: success()
      uses: SamKirkland/web-deploy@v1
      with:
        password: ${{ secrets.ftp_password }}
        target-server: ${{ secrets.SSH_SERVER }}
        remote-user: ${{ secrets.SSH_USER }}
        private-ssh-key: ${{ secrets.SSH_KEY }}
        destination-path: ~/public_html/teste/